<?php

use Illuminate\Database\Seeder;

class DsMenuTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ds_menu')->delete();
        
        \DB::table('ds_menu')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_name' => '系统设置',
                'parent_id' => 33,
                'route' => '系统设置',
                'm_name' => '系统设置',
                'c_name' => '系统设置',
                'a_name' => '系统设置',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_name' => '菜单管理',
                'parent_id' => 1,
                'route' => 'manage/menu',
                'm_name' => 'Manage',
                'c_name' => 'MenuController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_name' => '添加菜单',
                'parent_id' => 2,
                'route' => 'manage/menu/add',
                'm_name' => 'Manage',
                'c_name' => 'MenuController',
                'a_name' => 'add',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_name' => '编辑菜单',
                'parent_id' => 2,
                'route' => 'manage/menu/edit',
                'm_name' => 'Manage',
                'c_name' => 'MenuController',
                'a_name' => 'edit',
                'sort_num' => 2,
                'is_show' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_name' => '删除菜单',
                'parent_id' => 2,
                'route' => 'manage/menu/del',
                'm_name' => 'Manage',
                'c_name' => 'MenuController',
                'a_name' => 'del',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_name' => '用户管理',
                'parent_id' => 33,
                'route' => 'manage/user',
                'm_name' => 'Manage',
                'c_name' => 'UserController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_name' => '用户组管理',
                'parent_id' => 1,
                'route' => 'manage/group',
                'm_name' => 'Manage',
                'c_name' => 'GroupController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_name' => '增加用户组',
                'parent_id' => 7,
                'route' => 'manage/group/add',
                'm_name' => 'Manage',
                'c_name' => 'GroupController',
                'a_name' => 'add',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_name' => '编辑用户组',
                'parent_id' => 7,
                'route' => 'manage/group/edit',
                'm_name' => 'Manage',
                'c_name' => 'GroupController',
                'a_name' => 'edit',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_name' => '添加用户',
                'parent_id' => 6,
                'route' => 'manage/register',
                'm_name' => 'manage',
                'c_name' => 'LoginController',
                'a_name' => 'register',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_name' => '用户列表',
                'parent_id' => 6,
                'route' => 'manage/user/index',
                'm_name' => 'manage',
                'c_name' => 'UserController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_name' => '设置用户组权限',
                'parent_id' => 7,
                'route' => 'manage/group/setRole',
                'm_name' => 'Manage',
                'c_name' => 'GroupController',
                'a_name' => 'setRole',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_name' => '训练科目',
                'parent_id' => 33,
                'route' => '训练科目',
                'm_name' => '训练科目',
                'c_name' => '训练科目',
                'a_name' => '训练科目',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_name' => '科目管理',
                'parent_id' => 13,
                'route' => 'manage/subject/index',
                'm_name' => 'Manage',
                'c_name' => 'SubjectController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_name' => '课程管理',
                'parent_id' => 13,
                'route' => 'manage/course/index',
                'm_name' => 'Manage',
                'c_name' => 'CourseController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_name' => '添加科目',
                'parent_id' => 14,
                'route' => 'manage/subject/add',
                'm_name' => 'Manage',
                'c_name' => 'SubjectController',
                'a_name' => 'add',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'menu_name' => '编辑科目',
                'parent_id' => 14,
                'route' => 'manage/subject/edit',
                'm_name' => 'Manage',
                'c_name' => 'SubjectController',
                'a_name' => 'edit',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_name' => '删除科目',
                'parent_id' => 14,
                'route' => 'manage/subject/del',
                'm_name' => 'Manage',
                'c_name' => 'SubjectController',
                'a_name' => 'del',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'menu_name' => '添加课程',
                'parent_id' => 15,
                'route' => 'manage/course/add',
                'm_name' => 'Manage',
                'c_name' => 'CourseController',
                'a_name' => 'add',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'menu_name' => '编辑课程',
                'parent_id' => 15,
                'route' => 'manage/course/edit',
                'm_name' => 'Manage',
                'c_name' => 'CourseController',
                'a_name' => 'edit',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'menu_name' => '删除课程',
                'parent_id' => 15,
                'route' => 'manage/course/del',
                'm_name' => 'Manage',
                'c_name' => 'CourseController',
                'a_name' => 'del',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'menu_name' => '设备与商家',
                'parent_id' => 33,
                'route' => '设备与商家',
                'm_name' => '设备与商家',
                'c_name' => '设备与商家',
                'a_name' => '设备与商家',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'menu_name' => '商家管理',
                'parent_id' => 22,
                'route' => 'manage/company',
                'm_name' => 'Manage',
                'c_name' => 'CompanyController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'menu_name' => '添加',
                'parent_id' => 23,
                'route' => 'manage/company/add',
                'm_name' => 'Manage',
                'c_name' => 'CompanyController',
                'a_name' => 'add',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'menu_name' => '编辑',
                'parent_id' => 23,
                'route' => 'manage/company/edit',
                'm_name' => 'Manage',
                'c_name' => 'CompanyController',
                'a_name' => 'edit',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'menu_name' => '设备管理',
                'parent_id' => 22,
                'route' => 'manage/machine',
                'm_name' => 'Manage',
                'c_name' => 'MachineController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'menu_name' => '添加设备',
                'parent_id' => 26,
                'route' => 'manage/machine/add',
                'm_name' => 'Manage',
                'c_name' => 'MachineController',
                'a_name' => 'add',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'menu_name' => '编辑',
                'parent_id' => 26,
                'route' => 'manage/machine/edit',
                'm_name' => 'Manage',
                'c_name' => 'MerchantController',
                'a_name' => 'edit',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'menu_name' => '其他管理',
                'parent_id' => 33,
                'route' => '其他管理',
                'm_name' => '其他管理',
                'c_name' => '其他管理',
                'a_name' => '其他管理',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'menu_name' => '设备报修',
                'parent_id' => 29,
                'route' => 'manage/machineBug',
                'm_name' => 'Manage',
                'c_name' => 'MachineBug',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'menu_name' => '课程建议管理',
                'parent_id' => 29,
                'route' => 'manage/courseAdvice',
                'm_name' => 'Manage',
                'c_name' => 'CourseAdviceController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'menu_name' => '添加',
                'parent_id' => 31,
                'route' => 'manage/courseAdvice/add',
                'm_name' => 'Manage',
                'c_name' => 'CourseAdviceController',
                'a_name' => 'add',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'menu_name' => '后台',
                'parent_id' => 0,
                'route' => '后台',
                'm_name' => 'Manage',
                'c_name' => '后台',
                'a_name' => '后台',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'menu_name' => '前台',
                'parent_id' => 0,
                'route' => '前台',
                'm_name' => 'Home',
                'c_name' => '前台',
                'a_name' => '前台',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'menu_name' => '系统管理',
                'parent_id' => 34,
                'route' => 'admin',
                'm_name' => 'Home',
                'c_name' => 'AdminManage',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'menu_name' => '注册',
                'parent_id' => 35,
                'route' => 'admin/register',
                'm_name' => 'Home',
                'c_name' => 'AdminManage',
                'a_name' => 'register',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'menu_name' => '生成卡片号码',
                'parent_id' => 35,
                'route' => 'admin/getCardNum',
                'm_name' => 'Home',
                'c_name' => 'AdminController',
                'a_name' => 'getCardNum',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'menu_name' => '管理员统计',
                'parent_id' => 35,
                'route' => 'admin/statistics',
                'm_name' => 'Home',
                'c_name' => 'AdminStatisticsController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'menu_name' => '课程管理',
                'parent_id' => 34,
                'route' => 'course',
                'm_name' => 'Home',
                'c_name' => 'CourseController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'menu_name' => '无卡查询',
                'parent_id' => 34,
                'route' => 'noCard',
                'm_name' => 'Home',
                'c_name' => 'NoCardQueryController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'menu_name' => '补卡',
                'parent_id' => 35,
                'route' => 'admin/fillCard',
                'm_name' => 'Home',
                'c_name' => 'AdminController',
                'a_name' => 'fillCard',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'menu_name' => '基础信息',
                'parent_id' => 38,
                'route' => 'admin/statistics/userList',
                'm_name' => 'Home',
                'c_name' => 'AdminStatisticsController',
                'a_name' => 'userList',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'menu_name' => '科目二',
                'parent_id' => 38,
                'route' => 'admin/statistics/subject2List',
                'm_name' => 'Home',
                'c_name' => 'AdminStatisticsController',
                'a_name' => 'subject2List',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'menu_name' => '科目三',
                'parent_id' => 38,
                'route' => 'admin/statistics/subject3List',
                'm_name' => 'Home',
                'c_name' => 'AdminStatisticsController',
                'a_name' => 'subject3List',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'menu_name' => '删除用户',
                'parent_id' => 35,
                'route' => 'admin/delUser',
                'm_name' => 'Home',
                'c_name' => 'AdminController',
                'a_name' => 'delUser',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'menu_name' => '管理员修改用户',
                'parent_id' => 35,
                'route' => 'admin/editUser',
                'm_name' => 'Home',
                'c_name' => 'AdminController',
                'a_name' => 'editUser',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'menu_name' => '查询时长',
                'parent_id' => 35,
                'route' => 'admin/queryLength',
                'm_name' => 'Home',
                'c_name' => 'AdminController',
                'a_name' => 'queryLength',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'menu_name' => '报修',
                'parent_id' => 35,
                'route' => 'admin/repair',
                'm_name' => 'Home',
                'c_name' => 'AdminController',
                'a_name' => 'repair',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'menu_name' => '用户管理',
                'parent_id' => 34,
                'route' => 'user',
                'm_name' => 'Home',
                'c_name' => 'UserController',
                'a_name' => 'index',
                'sort_num' => 0,
                'is_show' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'menu_name' => '上机注意事项',
                'parent_id' => 49,
                'route' => 'user/helpShangji',
                'm_name' => 'Home',
                'c_name' => 'UserController',
                'a_name' => 'helpShangji',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'menu_name' => '设备注意事项',
                'parent_id' => 49,
                'route' => 'user/helpShebei',
                'm_name' => 'Home',
                'c_name' => 'UserController',
                'a_name' => 'helpShebei',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'menu_name' => '训练注意事项',
                'parent_id' => 49,
                'route' => 'user/helpXunlian',
                'm_name' => 'Home',
                'c_name' => 'UserController',
                'a_name' => 'helpXunlian',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'menu_name' => '其他注意事项',
                'parent_id' => 49,
                'route' => 'user/helpQita',
                'm_name' => 'Home',
                'c_name' => 'UserController',
                'a_name' => 'helpQita',
                'sort_num' => 0,
                'is_show' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'menu_name' => '获取剩余时长',
                'parent_id' => 49,
                'route' => 'user/getRemainingTime',
                'm_name' => 'Home',
                'c_name' => 'UserController',
                'a_name' => 'getRemainingTime',
                'sort_num' => 0,
                'is_show' => 0,
            ),
        ));
        
        
    }
}
